export const spotlightGrains = [
  {
    id: 'ragi',
    num: '01',
    badge: 'Calcium Champion',
    title: 'Ragi',
    aka: 'Finger Millet · రాగి',
    desc: 'One of the oldest cultivated grains in India, ragi has been a staple of South Indian kitchens for over 3,000 years. Dense, earthy, and incredibly nourishing — it forms the backbone of our breakfast menu.',
    benefit: 'Ragi is the richest plant source of calcium — surpassing dairy per gram — and has one of the lowest glycemic indexes of any grain.',
    nutrients: [
      { label: 'Calcium',  val: 92, color: '#C88A2A' },
      { label: 'Iron',     val: 65, color: '#7B4F1E' },
      { label: 'Fibre',    val: 70, color: '#4A7C3F' },
      { label: 'Protein',  val: 55, color: '#5C8C3A' },
    ],
    dishes: [
      { name: 'Ghee Karam Idli (2 pcs)', tag: 'Breakfast', price: '₹50' },
      { name: 'Ghee Ragi Dosa',          tag: 'Classic',   price: '₹70' },
      { name: 'Ragi Egg Dosa',           tag: 'Special',   price: '₹70' },
      { name: 'Ragi Idli (4 pcs)',        tag: 'Light',     price: '₹50' },
    ],
  },
  {
    id: 'jowar',
    num: '02',
    badge: 'Gluten Free',
    title: 'Jowar',
    aka: 'Sorghum · జొన్నలు',
    desc: 'Known as the "new quinoa" in wellness circles, jowar is a powerhouse of antioxidants and dietary fibre. Native to Africa and cultivated in the Deccan Plateau for millennia, it thrives in the same soil as our city.',
    benefit: 'Rich in polyphenols that help reduce oxidative stress. Its high fibre content promotes gut health and keeps cholesterol levels in check.',
    nutrients: [
      { label: 'Fibre',    val: 85, color: '#4A7C3F' },
      { label: 'Protein',  val: 72, color: '#5C8C3A' },
      { label: 'Iron',     val: 60, color: '#7B4F1E' },
      { label: 'Calcium',  val: 48, color: '#C88A2A' },
    ],
    dishes: [
      { name: 'Millet Upma (Pongal)',      tag: 'Morning',  price: '₹80' },
      { name: 'Ghee Millet Upma (Pongal)', tag: 'Premium',  price: '₹110' },
      { name: 'Millets Punugulu',           tag: 'Evening',  price: '₹60' },
      { name: 'Jowar Pesarattu',            tag: 'Classic',  price: '₹70' },
    ],
  },
  {
    id: 'bajra',
    num: '03',
    badge: 'Iron Rich',
    title: 'Bajra',
    aka: 'Pearl Millet · సజ్జలు',
    desc: 'Bajra is the grain of endurance — farmers in the Rajasthani desert and Andhra fields alike have relied on it for sustained energy through long working days. Its deep, nutty flavour is unmistakable.',
    benefit: 'Among the highest iron content of any cereal grain. Ideal for combating anaemia and boosting haemoglobin — especially beneficial for women and growing children.',
    nutrients: [
      { label: 'Iron',     val: 90, color: '#7B4F1E' },
      { label: 'Magnesium',val: 78, color: '#3B6B30' },
      { label: 'Protein',  val: 68, color: '#5C8C3A' },
      { label: 'Fibre',    val: 62, color: '#4A7C3F' },
    ],
    dishes: [
      { name: 'Millet Upma (Pongal)',  tag: 'Hearty',    price: '₹80' },
      { name: 'Uggani Bajji',          tag: 'Street',    price: '₹70' },
      { name: 'Millets Mirchi',        tag: 'Spicy',     price: '₹60' },
      { name: 'Madhur Wada',           tag: 'Crispy',    price: '₹60' },
    ],
  },
  {
    id: 'foxtail',
    num: '04',
    badge: 'Protein Dense',
    title: 'Foxtail',
    aka: 'Foxtail Millet · కొర్రలు',
    desc: 'Called "korralu" in Telugu, foxtail millet is a beloved grain of Andhra Pradesh — woven into local food culture as a natural rice substitute. Its mild, slightly sweet taste makes it the most versatile millet we work with.',
    benefit: 'Highest protein density among common millets. Packed with B vitamins that support brain and nervous system health. Excellent for diabetics as a daily rice alternative.',
    nutrients: [
      { label: 'Protein',   val: 88, color: '#5C8C3A' },
      { label: 'B Vitamins',val: 80, color: '#C88A2A' },
      { label: 'Fibre',     val: 66, color: '#4A7C3F' },
      { label: 'Iron',      val: 55, color: '#7B4F1E' },
    ],
    dishes: [
      { name: 'Ghee Millet Upma (Pongal)', tag: 'Premium',   price: '₹110' },
      { name: 'Millet Upma Dosa',          tag: 'Classic',   price: '₹70' },
      { name: 'Millets Upma Pesarattu',    tag: 'Fusion',    price: '₹80' },
      { name: 'Butter Millet Upma Dosa',   tag: 'Indulgent', price: '₹90' },
    ],
  },
];
